spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/sampledb
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
